project:
  type: website
  output-dir: _site  # this matches your deploy target

website:
  title: "Recipe Browser"
  navbar: false      # or true if you later want navigation

format:
  html:
    theme: default
    css: styles.css
    include-in-header: fonts.html